language: node_js
node_js:
   - "0.12"
   - "0.10"

env:
  global:
    - POSTGRESQL_URL="postgres://postgres@localhost:5432/medicdata"
    - POSTGRESQL_TABLE="couchdata"
    - POSTGRESQL_COLUMN="jsondata"
    - COUCHDB_URL="http://localhost:5984/medic/_all_docs?include_docs=true"

sudo: required

services:
   - couchdb

addons:
   - postgresql: "9.4"

before_script:
   - psql -c "CREATE DATABASE medicdata WITH OWNER postgres;" -U postgres
   - which psql
   - psql --version
   - psql -d ${POSTGRESQL_URL} -c "\conninfo"
   - psql -d ${POSTGRESQL_URL} -c "CREATE TABLE couchdata (jsondata JSONB);"
   - psql -d ${POSTGRESQL_URL} -c "SELECT * FROM pg_type WHERE typname LIKE '%json%';"

script:
   - ./replace_couch.sh
   - grunt ci

comments:
  notifications:
    webhooks:
      urls:
        - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
      on_success: change
      on_failure: always
    email:
      recipients:
        - dev@medicmobile.org
