language: node_js
node_js:
   - "0.12"
   - "0.10"

env:
  global:
    - POSTGRESQL_URL="postgres://medictest:password@localhost:5432/medicdata"
    - POSTGRESQL_TABLE="couchdata"
    - POSTGRESQL_COLUMN="json"
    - COUCHDB_URL="https://localhost:5984/medicdata"
    - DEMOS_COUCHDB="https://localhost:5984/medicdata"
    - PRELOAD_APP_DATA="diy"
    - PRELOAD_APP_MARKET="release"

sudo: required

services:
   - couchdb

addons:
   - postgresql: "9.4"

before_script:
   - psql -c "CREATE ROLE medictest WITH LOGIN PASSWORD 'password';" -U postgres
   - psql -c "CREATE DATABASE medicdata WITH OWNER medictest;" -U postgres
   - npm link ./medic-data
   - npm install gardener -g
   - npm install garden-core -g
   - npm install

script:
   - cd medic-data && make load
   - node `which grunt` ci

comments:
  notifications:
    webhooks:
      urls:
        - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
      on_success: change
      on_failure: always
    email:
      recipients:
        - dev@medicmobile.org
