language: node_js
node_js:
   - "0.12"
   - "0.10"
   - "5"

env:
  global:
    - POSTGRESQL_URL="postgres://postgres@localhost:5432/medicdata"
    - POSTGRESQL_TABLE="couchdb"
    - POSTGRESQL_COLUMN="doc"
    - COUCHDB_URL="http://localhost:5984/medic/_all_docs"

sudo: required

services:
   - couchdb

addons:
   postgresql: "9.4"

before_script:
   - psql -c "CREATE ROLE full_access;" -U postgres
   - psql -c "CREATE DATABASE medicdata WITH OWNER postgres;" -U postgres

script:
   - ./bin/replace_couch.sh
   - grunt ci

notifications:
  webhooks:
    urls:
      - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    on_success: change
    on_failure: always
  email:
    recipients:
      - dev@medicmobile.org
